### ISSUE TITLE
Where do the version numbers come from or get synced from?

### ISSUE THREAD

**Issue by ericclemmons** [guigrpa/oao#25]
When sub-packages reference another one, I'm currently using `*` but dunno if that's kept in sync somehow?

(My project currently has no tags)

**Comment by guigrpa** [comment]
Use version ranges (such as `*`, `^2.0.0`, `3.x`, `~1.2.3`) just as you would with external dependencies, but consider that:

* Those ranges will be honored by npm, yarn, etc. when your users install your published sub-packages.

* They will *not* be honored by oao in your monorepo installation, since the internal dependencies will be `yarn link`ed rather than installed.
