### ISSUE TITLE
Add a `run` command to the CLI

### ISSUE THREAD

**Issue by Inkdpixels** [guigrpa/oao#54]
Hey @guigrpa - Awesome job with this CLI - Really enjoying it so far! :)

The only thing I currently am missing is a `run` command similar to the `lerna run` command. Basically it would iterate through all packages, check if the provided script name is within the `package.json` and if that is the case it would execute a `yarn run <script-name>`.

Would you be up for such a contribution? I would be willing to do it in the next few days and create a PR to this repository! :)

**Comment by guigrpa** [comment]
I understand the difference is that this new command would run a yarn script, rather than a shell command (as in `oao all`), is that correct? Right now, you can do that with something like `oao all "yarn my-script"` (except that it will fail by default on subpackages that don't have a `my-script` script).

I think it's an interesting addition. Maybe use a more descriptive name, like `oao all-script` (to emphasise the similarity with `oao all`) or `oao run-script`?

Thanks a lot for the proposal!

**Comment by Inkdpixels** [comment]
@guigrpa Sure! My initial take was to get the transition from `lerna` to `oao` a bit smoother, hence the proposal having `run` as the command name. But you are totally right, `run-script` is way more descriptive so I would be totally okay with it! 😀
